export const MOVE_TO_ANSWER = "MOVE_TO_ANSWER";
export const MOVE_TO_QUESTION = "MOVE_TO_QUESTION";
export const TOGGLE_MATCHED = "TOGGLE_MATCHED";
export const TOGGLE_VALIDATING = "TOGGLE_VALIDATING";
export const START_VALIDATE_ANSWER = "START_VALIDATE_ANSWER";
export const END_VALIDATE_ANSWER = "END_VALIDATE_ANSWER";
